name: Build

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/security-scanning.yml
      - .github/workflows/skipped-security-scanning.yml
      - .github/workflows/skipped-workflow.yml
      - '.vscode/**'
      - .editorconfig
      - LICENSE
      - README.md

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Handling skipped but required check, see https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks"
