name: "Code scanning results"

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/skipped-security-scanning.yml
      - .github/workflows/skipped-workflow.yml
      - .github/workflows/workflow.yml
      - '.vscode/**'
      - 'deploy/**'
      - LICENSE
      - README.md

jobs:
  code-ql:
    name: CodeQL
    runs-on: ubuntu-latest
    steps:
      - run: echo "Handling skipped but required check, see https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks"
